Repository drazisil/buoy, pull requests merged in 2022-08, with the labels that each got.

#5 Add xo
  .vscode/extensions.json
  .vscode/settings.json
  lib/container-registry-client.js
  lib/containerRegistryClient.js
  package-lock.json
  package.json
  src/docker-registry-reader.js
  src/index.js
  test/index.js
  test/loader.js
Labels: size/XL

#4 Add publish workflow
  .github/workflows/ghpages.yml
Labels: size/S

#7 Add missing docs
  .vscode/settings.json
  jsdocconf.json
  lib/container-registry-client.js
  src/docker-registry-reader.js
Labels: size/S

#8 Add Codecov
  .github/workflows/node.js.yml
Labels: size/S

#10 Add-bin
  .gitignore
  bin/cli.js
  package-lock.json
  package.json
  src/index.js
  test/index.js
  tmp/.gitkeep
Labels: size/L

#11 Add-undici
  bin/cli.js
  lib/container-registry-client.js
  package-lock.json
  package.json
Labels: size/S
